title:               Dev Warehous
description:         'A blog for trial and error'
tagline:             'A blog for trial and error'
paginate:            5

url:                 https://sejunkwonme.github.io
baseurl:             ""
permalink:           /:year/:month/:day/:title/

exclude:
  - .gitignore
  - CNAME
  - README.md
  - .tool-versions
include:
  - .well-known

author:
  name:              Sejun Kwon
  email:             sejunkwon@outlook.com
  url:               https://sejunkwonme.github.io

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-gist

version:             1.0

github:
  repo: https://github.com/sejunkwonme/sejunkwonme.github.io

repository: sejunkwonme/sejunkwonme.github.io